#
# simple-app.yml
#
apiVersion: kappctrl.k14s.io/v1alpha1

# We're defining an app...
kind: App
metadata:
  name: viji-app
  namespace: default
spec:

  # What service account will run this app?
  serviceAccountName: default-ns-sa

  # Where is the app coming from?
  fetch:
  - git:
      url: git@github.com:vnarayanan12/kapp-simple-deployment.git
      ref: origin/main

      # We have a directory, named 'app', in the root of our repo.
      # Files describing the app (i.e. pod, service) are in that directory.
      subPath: app

  # No templating yet...
  template:
  - ytt: {}
  deploy:
  - kapp: {}

